# frontend/nginx.conf
server {
    listen 80;
    
    root /usr/share/nginx/html;
    
    # Enable Gzip compression
    gzip on;
    gzip_types text/plain application/xml text/css application/javascript;

    # SPA routing: Try to serve a file directly, if not, fallback to index.html
    location / {
        try_files $uri /index.html;
    }
}